name: Dev workflow
on:
  pull_request:
    branches:
      - main
env:
  docker_username: ${{ github.actor }} 
  docker_password: ${{ secrets.GITHUB_TOKEN }} 
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4 
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3 
        with:
          cache-read-only: false
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            /root/.gradle/caches
            /root/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build App
        run: ci/build-app.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .

  Test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - name: Test    
        run: ci/unit-test-app.sh
  Linter:
  # Needs fixing. Not working even though job succeeds.
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with: 
          name: code
          path: .
      - name: Run linting
        uses: super-linter/super-linter/slim@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main

  Docker:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with: 
          name: code
          path: .
      - name: build docker
        run: bash ci/build-docker.sh