name: Main workflow
on: 
  push:
    branches:
    - 'main'
    # paths
    # - '*.js' # Triggers when the push is to the main branch and there is atleast one change in a js file.

env:
  docker_username: ${{ github.actor }} 
  docker_password: ${{ secrets.GITHUB_TOKEN }} 
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - name: Build App
        run: ci/build-app.sh
      - name: Run Unit tests    
        run: ci/unit-test-app.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
  Linter:
  # Needs fixing. Not working even though job succeeds.
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with: 
          name: code
          path: .
      - name: Run linting
        uses: super-linter/super-linter/slim@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main

  Docker:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with: 
          name: code
          path: .
      - name: build docker
        run: bash ci/build-docker.sh
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }} 
      - name: Push
        uses: docker/build-push-action@v6
        with:
          context: app
          push: true
          tags: ghcr.io/${{ env.docker_username }}/micronaut-app:1.0-${{ env.GIT_COMMIT }},ghcr.io/${{ env.docker_username }}/micronaut-app:latest


  Component-Test:
    runs-on: ubuntu-latest
    needs: [Docker]
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with: 
        name: code
        path: .
    - name: Execute component test
      run: bash ci/component-test.sh
  

  Performance-Test:
    runs-on: ubuntu-latest
    needs: [Docker]
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with: 
        name: code
        path: .
    - name: Execute component test
      run: bash ci/performance-test.sh