name: Main workflow
on: 
  push:
    branches:
    - 'main'
    # paths
    # - '*.js' # Triggers when the push is to the main branch and there is atleast one change in a js file.

env:
  docker_username: ${{ github.actor }} 
  docker_password: ${{ secrets.GITHUB_TOKEN }} 
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - name: Build App
        run: ci/build-app.sh
      - name: Run Unit tests    
        run: ci/unit-test-app.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
  Linter:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with: 
          name: code
          path: .
      - name: Run linting
        uses: super-linter/super-linter/slim@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main

  Docker:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with: 
          name: code
          path: .
      - name: build docker
        run: bash ci/build-docker.sh
      - name: push docker
        run: bash ci/push-docker.sh