name: Main workflow
on: 
  push:
    branches:
    - 'main'
    # paths
    # - '*.js' # Triggers when the push is to the main branch and there is atleast one change in a js file.
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - name: Build App
        run: ci/build-app.sh
      - name: Run Unit tests    
        run: ci/unit-test-app.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
  Linter:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with: 
          name: code
      - name: Run linting
        uses: super-linter/super-linter/slim@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main