name: Reuse other workflow
on:
  workflow_dispatch:
    inputs:
      testInput:
        description: "Test input"
        required: true
        default: "test"


jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: "${{ github.event.inputs.testInput }}"
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
     # Because this is using github context (needs) the time is already set before passing on to the runner.
     # Unlike using Env Variables where the value is decided by reading from the environment and the value is not
     # displayed on the job log.
      - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"


